"""empty message

Revision ID: 176f693116f0
Revises: 
Create Date: 2018-10-19 12:07:05.343099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176f693116f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('b_title', sa.String(length=256), nullable=True),
    sa.Column('b_content', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_mail', sa.String(length=16), nullable=True),
    sa.Column('u_password', sa.Integer(), nullable=True),
    sa.Column('u_icon', sa.Integer(), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collect',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_id', sa.Integer(), nullable=True),
    sa.Column('b_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['b_id'], ['blog.id'], ),
    sa.ForeignKeyConstraint(['u_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collect')
    op.drop_table('user')
    op.drop_table('blog')
    # ### end Alembic commands ###
